# syntax=docker/dockerfile:1.7.0

ARG POSTGRES_VER=16.4-alpine3.20

FROM postgres:${POSTGRES_VER}

RUN apk add --no-cache file

ENV POSTGRES_HOST=${DB_URL:-localhost}
ENV POSTGRES_DB=${DB_NAME:-postgres}
ENV POSTGRES_USER=${DB_USER:-postgres}
ENV POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
ENV POSTGRES_PORT=${DB_PORT:-5432}

EXPOSE ${POSTGRES_PORT}

# ENTRYPOINT [ "/bin/bash" ]
# CMD [ "postgres", "-c", "listen_addresses='*'" ]
